"""PDF Report generation API endpoints."""
import io
from quart import Blueprint, request, send_file, jsonify

report_bp = Blueprint('report', __name__)


@report_bp.route('/generate', methods=['POST'])
async def generate_report():
    """Generate a PDF executive report."""
    try:
        from reportlab.lib.pagesizes import letter, A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        
        data = await request.get_json()
        company_name = data.get('company_name', 'Your Company')
        opportunities = data.get('opportunities', [])
        roi_summary = data.get('roi_summary', {})
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=0.75*inch, leftMargin=0.75*inch, topMargin=inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle('CustomTitle', parent=styles['Title'], fontSize=24, textColor=colors.HexColor('#6366f1'), spaceAfter=6)
        heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#1e1b4b'), spaceAfter=6)
        body_style = ParagraphStyle('CustomBody', parent=styles['Normal'], fontSize=10, leading=14)
        
        story = []
        story.append(Paragraph('FlowPilot AI', title_style))
        story.append(Paragraph(f'AI Automation Advisory Report', heading_style))
        story.append(Paragraph(f'Prepared for: {company_name}', body_style))
        story.append(Spacer(1, 0.3*inch))
        story.append(HRFlowable(width='100%', thickness=2, color=colors.HexColor('#6366f1')))
        story.append(Spacer(1, 0.2*inch))
        
        # ROI Summary
        story.append(Paragraph('Executive Summary – ROI Projections', heading_style))
        if roi_summary:
            roi_data = [
                ['Metric', 'Value'],
                ['Hours Saved Per Week', f"{roi_summary.get('total_hours_saved_per_week', 0)} hrs"],
                ['Annual Cost Savings', f"${roi_summary.get('annual_cost_savings', 0):,.0f}"],
                ['ROI', f"{roi_summary.get('roi_percentage', 0)}%"],
                ['Payback Period', f"{roi_summary.get('payback_months', 0)} months"],
                ['3-Year Value', f"${roi_summary.get('three_year_value', 0):,.0f}"],
            ]
            table = Table(roi_data, colWidths=[3*inch, 3*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f3ff')]),
                ('PADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(table)
            story.append(Spacer(1, 0.2*inch))
        
        # Opportunities
        story.append(Paragraph('Top Automation Opportunities', heading_style))
        for opp in opportunities[:5]:
            story.append(Paragraph(f"• <b>{opp.get('name')}</b> — {opp.get('department')}", body_style))
            story.append(Paragraph(f"  {opp.get('description', '')}", body_style))
            story.append(Paragraph(f"  Est. savings: ${opp.get('estimated_annual_cost_savings', 0):,.0f}/yr | ROI Score: {opp.get('roi_score', 0)}/100", body_style))
            story.append(Spacer(1, 0.1*inch))
        
        story.append(Spacer(1, 0.2*inch))
        story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e5e7eb')))
        story.append(Spacer(1, 0.1*inch))
        story.append(Paragraph('Generated by FlowPilot AI | flowpilot.ai', 
                                ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
        
        doc.build(story)
        buffer.seek(0)
        
        return await send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            attachment_filename=f'flowpilot-report-{company_name.lower().replace(" ", "-")}.pdf',
        )
    except Exception as e:
        return jsonify({'error': str(e), 'message': 'PDF generation failed. ReportLab may not be installed.'}), 500
